# Generated by Django 4.0 on 2022-02-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Admin_Login',
        ),
    ]
