# Generated by Django 4.0 on 2022-02-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_rename_note_admin_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_Login',
            new_name='AdminLogin',
        ),
    ]
